name: Metrics
on:
  # Se ejecuta cada día a las 00:00
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:
  # Se ejecuta cuando haces push a la rama main (opcional)
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Opciones de diseño (puedes cambiarlas)
          user: pminmic
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 4